spring:
  profiles:
    active: test
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/H2_repo/valid
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.valid.practice.web.api: debug
    org.hibernate.SQL: debug

server:
  port: 8083